### ISSUE TITLE
How to use as a role, and overwrite just a few default variables

### ISSUE THREAD

**Issue by viktorsmari** [mrlesmithjr/ansible-cassandra#2]
I have a cass04.yml file with:

```
- hosts: cass04
  become: true
  vars:
    telegraf_hostname: cass04
    cassandra:
      config: true
    cassandra_configuration:
      cluster_name: mycluster
      authenticator: PasswordAuthenticator
      endpoint_snitch: GossipingPropertyFileSnitch
      rpc_address: 0.0.0.0
      listen_address: 192.168.195.49

      #seeds: 192.168.192.39
      #name: cass04

  roles:
    - cassandra
```
Which I run with `ansible-playbook cass04.yml`

What is this playbook missing in order to be able to overwrite the default role variables?
Can you add an example to the documentation?
